# version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mighty_pong_net

  web:
    build: .
    command: gunicorn --workers=3 --bind=0.0.0.0:8000 web.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    networks:
      - mighty_pong_net

volumes:
  postgres_data:

networks:
  mighty_pong_net:
    driver: bridge
