volumes:
  postgres_data:

networks:
  default:
    name: app-net
    external: false
  shared-net:
    name: shared-net
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  web:
    container_name: website
    build: ./srcs
    command: ["/app/setup.sh"]
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DEVELOPMENT=True
      - DJANGO_SECRET_KEY
      - DJANGO_SETTINGS_MODULE
      - ADMIN_USER
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET
      - OAUTH2_REDIRECT_URI
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:12201"
    volumes:
      - ./config/ssl:/etc/ssl
    ports:
      - "8000:8000"
      - "3000:3000"
    restart: on-failure
    networks:
      - default
      - shared-net
