version: '3.8'
services:
  user_service:
    build: ./backend/user_service
    volumes:
      - ./backend/user_service/app:/app
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - users_db
    networks:
      - network

  users_db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRESS_DB}
      POSTGRES_USER: ${POSTGRESS_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASS}
    networks:
      - network
  
  # game_service:
  #   build: ./backend/game_service
  #   volumes:
  #     - ./backend/game_service:/app
  #   ports:
  #     - "3000:3000"
  #   command: npm start
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - network
      
volumes:
  postgres_data:

networks:
  network:
